language: php

php:
  - 5.6
  - 7.0

env:
  - COMPOSER_OPTIONS='install --prefer-source'

before_install:
  - composer self-update

before_script:
  - COMPOSER_ROOT_VERSION=dev-master composer $COMPOSER_OPTIONS

script:
  - ./bin/phpspec run --format=dot
  - ./bin/behat